name: Daily Bursary Update

on:
  schedule:
    - cron: "0 6 * * *"   # runs every day at 06:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run update script
        run: npm install && npm run update

      - name: Commit changes
        run: |
          git config --global user.name "auto-bot"
          git config --global user.email "bot@github.com"
          git add bursaries.json
          git diff --cached --quiet || git commit -m "auto update"
          git push
