name: Daily Bursary Update

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run update script
        run: npm install && npm run update

      - name: Commit changes
        run: |
          git config --global user.name "auto-bot"
          git config --global user.email "bot@github.com"

          git add bursaries.json

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "auto update"
            git push
          fi
